# Generated by Django 4.0.2 on 2022-05-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sskes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
