# Generated by Django 4.0.2 on 2022-05-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sskes_app', '0002_lesson_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
