# Generated by Django 4.0.2 on 2022-09-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sskes_app', '0006_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='lesson_assets/'),
        ),
    ]
