# Generated by Django 4.0.2 on 2022-09-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sskes_app', '0007_alter_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
