# Generated by Django 4.0.2 on 2022-09-22 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sskes_app', '0009_remove_course_slug_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentconnect',
            name='updated_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
