# Generated by Django 4.0.2 on 2022-09-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sskes_app', '0011_parentconnect_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentConnect',
        ),
    ]
