# Generated by Django 4.0.2 on 2022-09-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sskes_app', '0012_delete_parentconnect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
    ]
